SELECT COUNT(*) , CAMPUS_EVENT_NBR 
FROM PS_CAMPUS_MTG 
WHERE MEETING_DT = TO_DATE(:1,'YYYY-MM-DD') 
AND FACILITY_ID =:2 AND MEETING_TIME_START < DECODE(:3, NULL, TO_TIMESTAMP(NULL), TO_TIMESTAMP('1900-01-01-' || :3, 'YYYY-MM-DD-HH24.MI.SS.FF')) 
AND MEETING_TIME_END > DECODE(:4, NULL, TO_TIMESTAMP(NULL), TO_TIMESTAMP('1900-01-01-' || :4, 'YYYY-MM-DD-HH24.MI.SS.FF')) AND (DAY_OF_WK = '3') 
AND MEETING_DT NOT IN (SELECT HOLIDAY FROM PS_HOLIDAY_DATE WHERE HOLIDAY_SCHEDULE =:5 AND HOLIDAY = TO_DATE(:6,'YYYY-MM-DD') ) 
GROUP BY CAMPUS_EVENT_NBR<
